# Copier ce fichier vers .streamlit/secrets.toml
# Les valeurs sont déjà pré-remplies pour ton projet

[supabase]
url = "https://jdgirhqkikgruabnrbgf.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZ2lyaHFraWtncnVhYm5yYmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTk5OTYsImV4cCI6MjA2NDc5NTk5Nn0.LIi__kY3jBKKbCOdPSQj0aPAS8WQr4xdNlSkkU_XFd4"
